export enum PrismaLayerType {
  ClientOperation = 'prisma:client:operation',
  ClientConnect = 'prisma:client:connect',
  ClientSerialize = 'prisma:client:serialize',
  ClientTransaction = 'prisma:client:transaction',
  Engine = 'prisma:engine',
  EngineConnect = 'prisma:engine:connect',
  EngineDisconnect = 'prisma:engine:disconnect',
  EngineConnection = 'prisma:engine:connection',
  EngineSchema = 'prisma:engine:schema',
  EngineQuery = 'prisma:engine:db_query',
  EngineSerialize = 'prisma:engine:serialize',
  EngineItxRunner = 'prisma:engine:itx_runner',
  EngineItxQueryBuilder = 'prisma:engine:itx_query_builder',
  EngineResponseJsonSerialization = 'prisma:engine:response_json_serialization',
  JsQueryArgs = 'js:query:args',
  JsQuerySql = 'js:query:sql',
  JsQueryResult = 'js:query:result',
}
